on:
  rsshub_mini_dev:
    path: /smzdm/keyword/女装
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rsshub_mini_dev.outputs.title}}
          description: ${{on.rsshub_mini_dev.outputs.description}}
          link: ${{on.rsshub_mini_dev.outputs.link}}
        run: |
          echo title: $title
          echo description: $description
          echo link: $link
